---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/cv_studio
    - if [ -d "$DEPLOYPATH" ] && [ "$PWD" != "$DEPLOYPATH" ]; then /bin/cp -R * $DEPLOYPATH; fi
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
